/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.MouseAdapter;
import java.awt.font.TextAttribute;
import java.util.HashMap;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import model.Dictionary;

/**
 *
 * @author Monkey-private
 */
public class MainUI extends javax.swing.JFrame implements IMainUI {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        tpMeaning.setEditable(false);
        tpMeaning.setCaretPosition(0);
        tpMeaning.setContentType("text/html");
        listIndex.setFont(new Font("Times New Roman", Font.BOLD, 15));
//        btnCopy.setBorderPainted(false);
        //btnCopy.setFocusPainted(false);
//        btnVE.setContentAreaFilled(false);
//        btnEV.setContentAreaFilled(false);
        HashMap<TextAttribute, Object> textAttrMap = new HashMap<TextAttribute, Object>();
        textAttrMap.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        textAttrMap.put(TextAttribute.FOREGROUND, Color.BLUE);

        btnVE.setFont( btnVE.getFont().deriveFont(textAttrMap));
        btnEV.setFont(btnEV.getFont().deriveFont(textAttrMap));
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jButton4 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnelDictionary = new javax.swing.JPanel();
        btnVE = new javax.swing.JButton();
        btnEV = new javax.swing.JButton();
        btnListen = new javax.swing.JButton();
        btnTranslateSentence = new javax.swing.JButton();
        pnelHelp = new javax.swing.JPanel();
        btnAbout = new javax.swing.JButton();
        btnHelpContents = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listIndex = new javax.swing.JList<String>();
        tfSearch = new javax.swing.JTextField();
        lbSearch = new javax.swing.JLabel();
        lbListWords = new javax.swing.JLabel();
        lbListResults = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listResults = new javax.swing.JList<String>();
        btnSettings = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbWord = new javax.swing.JLabel();
        btnSound = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tpMeaning = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton4)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jButton4)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IDictionary ");

        btnVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/vietnam_flag.png"))); // NOI18N
        btnVE.setText("Viet-Eng");
        btnVE.setToolTipText("Using Vietnamese - English Dictionary");

        btnEV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/united_states_of_america.png"))); // NOI18N
        btnEV.setText("Eng-Viet");
        btnEV.setToolTipText("Using English - Vietnamese Dictionary");

        btnListen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lsongs.png"))); // NOI18N
        btnListen.setText("Listen sentences");

        btnTranslateSentence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bing_alt_1.png"))); // NOI18N
        btnTranslateSentence.setText("Translate Online");

        javax.swing.GroupLayout pnelDictionaryLayout = new javax.swing.GroupLayout(pnelDictionary);
        pnelDictionary.setLayout(pnelDictionaryLayout);
        pnelDictionaryLayout.setHorizontalGroup(
            pnelDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelDictionaryLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(btnVE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTranslateSentence)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnelDictionaryLayout.setVerticalGroup(
            pnelDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelDictionaryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnelDictionaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVE, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEV, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnListen, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnTranslateSentence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dictionary & Culture", pnelDictionary);

        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/info.png"))); // NOI18N
        btnAbout.setText("About");

        btnHelpContents.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/system_help.png"))); // NOI18N
        btnHelpContents.setText("Help Contents");
        btnHelpContents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpContentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnelHelpLayout = new javax.swing.GroupLayout(pnelHelp);
        pnelHelp.setLayout(pnelHelpLayout);
        pnelHelpLayout.setHorizontalGroup(
            pnelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelHelpLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnHelpContents, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnelHelpLayout.setVerticalGroup(
            pnelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHelpContents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Help", pnelHelp);

        listIndex.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listIndex);

        tfSearch.setToolTipText("Enter word here");

        lbSearch.setBackground(new java.awt.Color(102, 204, 255));
        lbSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbSearch.setForeground(new java.awt.Color(255, 204, 51));
        lbSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/find.png"))); // NOI18N
        lbSearch.setLabelFor(tfSearch);
        lbSearch.setText("Search");
        lbSearch.setBorder(new javax.swing.border.MatteBorder(null));

        lbListWords.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbListWords.setForeground(new java.awt.Color(255, 153, 51));
        lbListWords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/program_group.png"))); // NOI18N
        lbListWords.setLabelFor(listIndex);
        lbListWords.setText("Index");
        lbListWords.setBorder(new javax.swing.border.MatteBorder(null));
        lbListWords.setIconTextGap(10);

        lbListResults.setBackground(new java.awt.Color(102, 255, 102));
        lbListResults.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbListResults.setForeground(new java.awt.Color(255, 153, 0));
        lbListResults.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/document_open_recent.png"))); // NOI18N
        lbListResults.setLabelFor(listResults);
        lbListResults.setText("Results");
        lbListResults.setBorder(new javax.swing.border.MatteBorder(null));

        listResults.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listResults);

        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/setting1.png"))); // NOI18N
        btnSettings.setText("Settings");

        lbWord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/audio.png"))); // NOI18N
        btnSound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbWord, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSound, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(tpMeaning);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/vietnam_flag2.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbListWords, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbListResults, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(tfSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSettings))
                    .addComponent(jScrollPane4)
                    .addComponent(jTabbedPane1)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 476, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addComponent(btnSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(lbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbListWords, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbListResults, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4)))
        );
        jDesktopPane1.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(tfSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbListWords, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lbListResults, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnSettings, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSoundActionPerformed

    private void btnHelpContentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpContentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelpContentsActionPerformed
    
    public void setStyleButonEV(){
        
    }
    public void setStyleButtonVE(){
        
    }    //    @Override
//    public void setListIndexValueChanged(javax.swing.event.ListSelectionListener listener) {                                       
//        // TODO add your handling code here:
//        this.listIndex.addListSelectionListener(listener);
//    }                                      

    @Override
    public void setTfSearchKeyListener(java.awt.event.KeyListener listener) {                                     
        // TODO add your handling code here:
        this.tfSearch.addKeyListener(listener);
    }                                    

         
    @Override
    public void setBtnSettingsActionListener(java.awt.event.ActionListener listener) {                                            
        // TODO add your handling code here:
        this.btnSettings.addActionListener(listener);
    }                                           
    public void setListResultMouseAction(MouseAdapter listener){
        listResults.addMouseListener(listener);
    }
    public void setListResultKeyAction(KeyAdapter listener){
        listResults.addKeyListener(listener);
    }
    public JList getListRerult(){
        return this.listResults;
    }
                                          

    @Override
    public void setBtnTranslateSentenceActionListener(java.awt.event.ActionListener listener) {                                                     
        this.btnTranslateSentence.addActionListener(listener);
    }                                                    

    @Override
    public void setBtnVEActionListener(java.awt.event.ActionListener listener) {                                             
        // TODO add your handling code here:
        this.btnVE.addActionListener(listener);
    }                                            

    @Override
    public void setBtnEVActionListener(java.awt.event.ActionListener listener) {                                             
        // TODO add your handling code here:
        this.btnEV.addActionListener(listener);
    }                                            

    @Override
    public void setBtnListenActionListener(ActionListener listener) {                                          
        // TODO add your handling code here:
        this.btnListen.addActionListener(listener);
    }                                         

    @Override
    public void setBtnHelpContentsActionListener(java.awt.event.ActionListener listener) {                                                
        // TODO add your handling code here:
        this.btnHelpContents.addActionListener(listener);
    }  
    @Override
    public void setBtnAboutActionListener(java.awt.event.ActionListener listener) {
        this.btnAbout.addActionListener(listener);
    }
    public void setBtnSoundActionListener(ActionListener listener){
        btnSound.addActionListener(listener);
    }
    public void setTaMeaningAction(MouseAdapter listener){
        tpMeaning.addMouseListener(listener);
    }
    @Override
    public JList getListIndex(){
        return this.listIndex;
    }
    @Override
    public JTextPane getTaMeaning(){
        return this.tpMeaning;
    }
    @Override
    public JTextField getTfSearch(){
        return this.tfSearch;
    }
    public JLabel getLabelWord(){
        return lbWord;
    }
     public void setStateEV(){
         btnSound.setVisible(true);
         this.repaint();
     }
    public void setStateVE(){
        btnSound.setVisible(false);
        this.repaint();
    }
     public void updateUI(){
         this.repaint();
     }
    @Override
    public void setTextEng(){
        btnAbout.setText("About");
        btnEV.setText("Eng-Viet");
        btnHelpContents.setText("Help Contents");
        btnListen.setText("Listen");
        btnSettings.setText("Settings");
        btnTranslateSentence.setText("Translate Online");
        btnVE.setText("Viet-Eng");
        jButton4.setText(null);
        pnelDictionary.setName("Dictionary & Culture");
        pnelHelp.setName("Help");
//        this.repaint();
       
    }
    @Override
    public void setTextViet(){
        btnAbout.setText("Thông tin");
        btnEV.setText("Anh-Việt");
        btnHelpContents.setText("Trợ giúp");
        btnListen.setText("Nghe");
        btnSettings.setText("Cài đặt");
        btnTranslateSentence.setText("Dịch online");
        btnVE.setText("Việt-Anh");
        jButton4.setText(null);
        pnelDictionary.setName("Chọn từ điển");
        pnelHelp.setName("Trợ giúp");
//         this.repaint();
    }
    

//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAbout;
    private javax.swing.JButton btnEV;
    private javax.swing.JButton btnHelpContents;
    private javax.swing.JButton btnListen;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnSound;
    private javax.swing.JButton btnTranslateSentence;
    private javax.swing.JButton btnVE;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbListResults;
    private javax.swing.JLabel lbListWords;
    private javax.swing.JLabel lbSearch;
    private javax.swing.JLabel lbWord;
    private javax.swing.JList<String> listIndex;
    private javax.swing.JList<String> listResults;
    private javax.swing.JPanel pnelDictionary;
    private javax.swing.JPanel pnelHelp;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextPane tpMeaning;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setListMouseAction(MouseAdapter listener) {                                       
        // TODO add your handling code here:
        this.listIndex.addMouseListener(listener);
    }   
    @Override
    public void setListKeyAction(KeyAdapter listener){
        this.listIndex.addKeyListener(listener);
    }

    
}
